input = <<-INPUT
>Rosalind_6404
CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCC
TCCCACTAATAATTCTGAGG
>Rosalind_5959
CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCT
ATATCCATTTGTCAGCAGACACGC
>Rosalind_0808
CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGAC
TGGGAACCTGCGGGCAGTAGGTGGAAT
INPUT

puts "%s\n%0.6f%%" % input.gsub("\n", '').scan(/>(.*?\d{4})([^>]*)/).map { |n, s| [n, s.gsub(/A|T/, '').size.to_f * 100.0 / s.size.to_f] }.max_by {|n, p| p }